In [ ]:
#PRACTICAL QUESTIONS:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np
arr=np.random.randint(1,100,size=(3,3))
print('original array')
print(arr)
# Interchange rows and columns using np.transpose() function
arr_transposed=np.transpose(arr)
print('array after transposing')
print(arr_transposed)

original array
[[75 85  4]
 [82 80 35]
 [17 50 52]]
array after transposing
[[75 82 17]
 [85 80 50]
 [ 4 35 52]]


In [ ]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
import numpy as np
arr=np.array([11,22,33,44,55,66,77,88,99,111])
print('original array:')
print(arr)
# Reshape the array into a 2x5 array
reshaped_arr=arr.reshape(2,5)
print('2x5 array:')
print(reshaped_arr)
# Reshape the array into a 5x2 array
new_arr=arr.reshape(5,2)
print('5x2 array:')
print(new_arr)

original array:
[ 11  22  33  44  55  66  77  88  99 111]
2x5 array:
[[ 11  22  33  44  55]
 [ 66  77  88  99 111]]
5x2 array:
[[ 11  22]
 [ 33  44]
 [ 55  66]
 [ 77  88]
 [ 99 111]]


In [ ]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np
# Create a 4x4 NumPy array with random float values
arr_4x4=np.random.uniform(1,10,size=(4,4))
print('original 4x4 array')
print(arr_4x4)
# Add a border of zeros around the 4x4 array, resulting in a 6x6 array
arr_6x6=np.zeros((6,6))
arr_6x6[1:5,1:5]=arr_4x4
print ('array with zeros in there border modified to 6x6')
print(arr_6x6)

original 4x4 array
[[9.97740245 2.0707987  5.18037851 4.98296738]
 [9.36078733 7.34118947 1.23070057 5.6158883 ]
 [5.22690639 6.19983659 6.11072457 4.54093556]
 [6.66237801 8.24666136 9.66534856 8.04057413]]


In [ ]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np
arr=np.arange(10,61,5)
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


In [ ]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.
import numpy as np
arr = np.array(['pyThOn', 'NuMpy', 'pAndAs'])
# Apply uppercase transformation
uppercase_arr = np.array([x.upper() for x in arr])
print('uppercase array')
print(uppercase_arr)
# Apply lowercase transformation
lowercase_arr = np.array([x.lower() for x in arr])
print('lowercase array')
print(lowercase_arr)
# Apply title case transformation
title_arr = np.array([x.title() for x in arr])
print('title case array')
print(title_arr)


uppercase array
['PYTHON' 'NUMPY' 'PANDAS']
lowercase array
['python' 'numpy' 'pandas']
title case array
['Python' 'Numpy' 'Pandas']


In [ ]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np
arr = np.array(['lilac','beige','turquoise','crimson','white'])
# Insert a space between each character of every word in the array
arr_with_spaces = np.array(list(map(lambda x: ' '.join(x), arr)))
print(arr_with_spaces)

['l i l a c' 'b e i g e' 't u r q u o i s e' 'c r i m s o n' 'w h i t e']


In [ ]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division
import numpy as np
x=np.random.randint(1,5,(2,2))
y=np.random.randint(1,5,(2,2))
print ("original array 1:" )
print(x)
print("original array 2:")
print(y)
print('element wise addition')
print(x+y)
print('element wise subtraction')
print(x-y)
print('element wise multiplication')
print(x*y)
print('element wise division')
print(x/y)

original array 1:
[[1 1]
 [2 3]]
original array 2:
[[3 2]
 [2 4]]
element wise addition
[[4 3]
 [4 7]]
element wise subtraction
[[-2 -1]
 [ 0 -1]]
element wise multiplication
[[ 3  2]
 [ 4 12]]
element wise division
[[0.33333333 0.5       ]
 [1.         0.75      ]]


In [ ]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements
import numpy as np
#5x5 matrix
arr = np.eye(5)
# Print the entire matrix
print("Identity Matrix:")
print(arr)
# Extract and print the diagonal elements
diagonal_elements = np.diagonal(arr)
print("Diagonal Elements:")
print(diagonal_elements)

Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
[1. 1. 1. 1. 1.]


In [ ]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
#this array.
import numpy as np
import math
# Generate a NumPy array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1000, size=(100,))
print('Array of 100 random numbers:')
print(arr)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Find and display all prime numbers in the array
prime_numbers = [x for x in arr if is_prime(x)]
print('Prime numbers in the array:')
print(prime_numbers)

In [ ]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
#averages
import numpy as np
# Create a NumPy array representing daily temperatures for a month
arr = np.array([23, 21, 19, 22, 20, 18, 21,
19, 22, 20, 17, 18, 19, 20,
21, 19, 20, 21, 22, 23, 24,
25, 26, 27, 28, 29, 30, 31,
32, 33])
# Calculate and display the weekly averages
weekly_averages = np.array([np.mean(arr[i:i+7]) for i in range(0, len(arr), 7)])
print('Weekly averages:')
print(weekly_averages)