In [6]:
#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
#enhance Python's capabilities for numerical operations?
"""
NumPy(Numerical Python) is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform, and matrices.
NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
#advantages:
vectorized code is more concise and easier to read
fewer lines of code generally means fewer bugs
the code more closely resembles standard mathematical notation (making it easier, typically, to correctly code
mathematical constructs)
vectorization results in more “Pythonic” code. Without vectorization, our code would be littered with inefficient 
and difficult to read for loops.
"""

'\nNumPy(Numerical Python) is a Python library used for working with arrays.\nIt also has functions for working in domain of linear algebra, fourier transform, and matrices.\nNumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.\n#advantages:\nvectorized code is more concise and easier to read\nfewer lines of code generally means fewer bugs\nthe code more closely resembles standard mathematical notation (making it easier, typically, to correctly code\nmathematical constructs)\nvectorization results in more “Pythonic” code. Without vectorization, our code would be littered with inefficient \nand difficult to read for loops.\n'

In [2]:
#3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
#arrays.
import numpy as np
"""
1. Slicing with [::-1]:
This is the most basic and versatile method, applicable to any axis. It uses the stride notation
 [::-1] to reverse the element order.
 """
lis=[1,2,3,4,5,6,'a','b','c','d']
arr2=(np.array(lis))
print(arr2[::-1])
"""
2. FLIP:
The flip function allows you to specify the axis along which to reverse the elements.
"""
a=np.array([[1,2,3],[4,5,6]])
reversed_rows = np.flip(a,0)
print(reversed_rows) 
reversed_columns = np.flip(a,1)
print(reversed_columns)
"""
3. flipud and fliplr functions:
These functions are shortcuts for flipping arrays vertically (up-down) and horizontally (left-right) respectively.
 They are equivalent to flip(axis=0) and flip(axis=1) for 2D arrays.
 """
flipped_ud = np.flipud(a)#rows
print(flipped_ud) 
flipped_lr = np.fliplr(a)#column
print(flipped_lr)


['d' 'c' 'b' 'a' '6' '5' '4' '3' '2' '1']
[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]


In [7]:
#2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
#other?
'''MEAN:In numpy library, np.mean() is a function used to calculate arithmetic mean of the given array
along with the axis.
All elements have equal weight
Weight cannot be passed trough the parameter of the given function.
Syntax :
np.mean(arr, axis = None)'''
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("ARRAY:",arr)
print(np.mean(arr))#mean of array
'''AVERAGE():The arithmetic mean and weighted average calculations are more flexible with np.average().
It can calculate the weighted average if we pass the weight; if not, it returns the same value as np.mean().
This implies that the arithmetic mean is the result when we do not pass the weight condition.
Use this function when you have special cases where certain numbers carry more weight.
Syntax :
numpy.average(arr, axis = None, weights = None)'''
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array :",arr,)
print("AVERAGE: ",np.average(arr))
weight = np.array([4,5,6,12,15,10,2,8,19,20])
print("Weight average of Array : ",np.average(arr, weights=weight))

ARRAY: [ 1  2  3  4  5  6  7  8  9 10]
5.5
Array : [ 1  2  3  4  5  6  7  8  9 10]
AVERAGE:  5.5
Weight average of Array :  6.574257425742574


In [3]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
#in memory management and performance.
'''A data type in NumPy is used to specify the type of data stored in a variable.
We can check the datatype of Numpy array by using dtype.
 Then it returns the data type all the elements in the array.'''
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
data_type = arr.dtype
print("Data type:", data_type)
lis=[1,2,3,4,5,6,'a','b','c','d']
arr2=(np.array(lis))#numpy array can store only one data type
data_type=arr2.dtype
print('datatype:',data_type)


Data type: int64
datatype: <U21


In [4]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
""">>An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size.
 The number of dimensions and items in an array is defined by its shape, which is a tuple of N non-negative
  integers that specify the sizes of each dimension unlike list .
>>As with other container objects in Python, the contents of an ndarray can be accessed and modified by 
indexing or slicing the array.
>>numpy is a altogether separate module unlike list which is a data structure
>>Different ndarrays can share the same data, so that changes made in one ndarray may be visible in another."""
import numpy as np
lis=[1,2,3,4,5,6,'a','b','c','d']
arr2=(np.array(lis))#numpy array can store only one data type
print(arr2)

['1' '2' '3' '4' '5' '6' 'a' 'b' 'c' 'd']


In [5]:
#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
"""
Element-wise operation is possible Numpy array has various functions, methods, and variables, to ease our task of 
matrix computation.Elements of an array are stored contiguously in memory. For example,
 all rows of a two-dimensioned array must have the same number of columns.
  A three-dimensional array must have the same number of rows and columns on each card
1.Speed Boost
2.Memory Usage
3.Advanced Functions
4.Multidimensional Data
5.Broad Compatibility
6.Ease of Learning
7.Here's what else to consider
"""

"\nElement-wise operation is possible Numpy array has various functions, methods, and variables, to ease our task of \nmatrix computation.Elements of an array are stored contiguously in memory. For example,\n all rows of a two-dimensioned array must have the same number of columns.\n  A three-dimensional array must have the same number of rows and columns on each card\n1.Speed Boost\n2.Memory Usage\n3.Advanced Functions\n4.Multidimensional Data\n5.Broad Compatibility\n6.Ease of Learning\n7.Here's what else to consider\n"

In [8]:
#7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
#output.
'''vstack:
Vertical stacking of arrays is done by vstack() function in numpy library.
Syntax :
numpy.vstack((arr1, arr2, arr3,...))'''
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = np.vstack((array1, array2))
print(result)
'''hstack:
Horizontal stacking of arrays is done by hstack() function in numpy library.
Syntax :
numpy.hstack((arr1, arr2, arr3,...))'''
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = np.hstack((array1, array2))
print(result)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
#array dimensions.
'''fliplr:
Flip the array horizontally by fliplr() function in numpy library.
Syntax :
numpy.fliplr(arr)'''
import numpy as np
arr = np.array([[1, 2, 3], [4, 5,6], [7, 8, 9]])
print("Original array: ", arr)
print("Flipped array: ", np.fliplr(arr))
'''flipud:
Flip the array vertically by flipud() function in numpy library.
Syntax :
numpy.flipud(arr)'''
arr = np.array([[1, 2, 3], [4, 5,6], [7, 8, 9]])
print("Original array: ", arr)
print("Flipped array: ", np.flipud(arr))

In [ ]:
#9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
'''array_split:
Split the array into multiple sub-arrays by array_split() function in numpy library.
Syntax :
numpy.array_split(arr, indices_or_sections)'''
import numpy as np
arr = np.arange(11)  # Create an array of length 11
sub_arrays = np.array_split(arr,4)  # Split the array into 3 sub-arrays
print(sub_arrays)

arr_1=np.array(list('this is a array split'))
sub_arr=np.array_split(arr_1,5)
print(sub_arr)
"""Handling uneven splits:
If the length of the array is not exactly divisible by the number of sections, array_split() will handle the uneven split
by distributing the remaining elements as evenly as possible among the sub-arrays."""
arr = np.arange(15)
sub_arrays = np.array_split(arr, 4)
print(sub_arrays)

In [ ]:
#10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
#operations?
'''Vectorization:
Vectorization is a process in which a single operation is applied to all elements of an array at once
This approach eliminates the need for explicit loops, making computations faster and more efficient'''
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
squared_arr = arr ** 2
print(squared_arr)
'''Broadcasting
Broadcasting is a process in which an operation is applied to an array and a scalar value at once
This approach allows for efficient operations on arrays with different shapes'''
arr1 = np.array([1, 2, 3])  # shape (3,)
arr2 = np.array([[4], [5], [6]])  # shape (3, 1)
result = arr1 + arr2
print(result) 